/*
 * generated by Xtext
 */
package org.nanosite.remix.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RemixUiModule extends org.nanosite.remix.ui.AbstractRemixUiModule {
	public RemixUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
