/*
* generated by Xtext
*/
package org.nanosite.remix.ui.contentassist;

import org.nanosite.remix.ui.contentassist.AbstractRemixProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class RemixProposalProvider extends AbstractRemixProposalProvider {

}
