/*
 * generated by Xtext
 */
package org.nanosite.remix;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.nanosite.remix.valueconverter.RemixValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RemixRuntimeModule extends org.nanosite.remix.AbstractRemixRuntimeModule {

//	@Override
//	public Class<? extends IValueConverterService> bindIValueConverterService() {
//		return RemixValueConverterService.class;
//	}

}
